# Generated by Django 2.2.13 on 2020-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router_details',
            name='router_id',
            field=models.CharField(default=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='type_of_router',
            name='sap_id',
            field=models.CharField(default=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
